In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [3]:
data = {
    "Email_Length": [120, 450, 80, 600, 150, 700, 90, 550, 200, 800,
                     100, 650, 180, 720, 130, 500, 110, 900, 160, 750],

    "Links": [0, 5, 0, 8, 1, 10, 0, 7, 2, 12,
              0, 9, 1, 11, 0, 6, 0, 15, 1, 10],

    "Spam_Words": [1, 8, 0, 10, 2, 12, 0, 9, 3, 15,
                   1, 11, 2, 13, 0, 7, 1, 18, 2, 14],

    "Capital_Letters": [5, 30, 2, 40, 8, 50, 3, 35, 10, 60,
                        4, 45, 7, 55, 3, 28, 5, 70, 8, 48],

    "Spam": [
        0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
        0, 1, 0, 1, 0, 1, 0, 1, 0, 1
    ]
}

df = pd.DataFrame(data)

df

,Email_Length,Links,Spam_Words,Capital_Letters,Spam
0,120,0,1,5,0
1,450,5,8,30,1
2,80,0,0,2,0
3,600,8,10,40,1
4,150,1,2,8,0
5,700,10,12,50,1
6,90,0,0,3,0
7,550,7,9,35,1
8,200,2,3,10,0
9,800,12,15,60,1


In [4]:
X = df[
    [
        "Email_Length",
        "Links",
        "Spam_Words",
        "Capital_Letters"
    ]
]

y = df["Spam"]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

In [6]:
model = GaussianNB()

model.fit(X_train, y_train)

GaussianNB()

In [7]:
y_pred = model.predict(X_test)

print(y_pred)

[0 0 1 1 0]


In [8]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 1.0


In [9]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       1.00      1.00      1.00         2

    accuracy                           1.00         5
   macro avg       1.00      1.00      1.00         5
weighted avg       1.00      1.00      1.00         5



In [10]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[3 0]
 [0 2]]


In [11]:
new_email = [[700, 10, 12, 50]]

prediction = model.predict(new_email)

if prediction[0] == 1:
    print("Spam Email")
else:
    print("Not Spam")

Spam Email


c:\Users\thema\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


In [12]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [14]:
data = {
    "Age": [25, 35, 45, 50, 60, 30, 40, 55, 65, 28,
            48, 52, 33, 70, 58, 42, 37, 62, 29, 67],

    "BP": [118, 125, 140, 145, 165, 120, 135, 155, 170, 115,
           142, 150, 122, 175, 160, 130, 128, 168, 119, 172],

    "Sugar_Level": [90, 100, 130, 145, 180, 95, 115, 160, 200, 88,
                    135, 150, 105, 210, 175, 110, 102, 190, 92, 205],

    "Heart_Rate": [70, 75, 85, 88, 96, 72, 80, 92, 100, 68,
                   86, 90, 74, 105, 95, 78, 76, 98, 71, 102],

    "BMI": [22, 24, 28, 29, 32, 21, 26, 31, 34, 22,
            29, 30, 23, 35, 32, 25, 24, 33, 21, 34],

    "Disease": [
        0, 0, 1, 1, 1,
        0, 0, 1, 1, 0,
        1, 1, 0, 1, 1,
        0, 0, 1, 0, 1
    ]
}

df = pd.DataFrame(data)

df

,Age,BP,Sugar_Level,Heart_Rate,BMI,Disease
0,25,118,90,70,22,0
1,35,125,100,75,24,0
2,45,140,130,85,28,1
3,50,145,145,88,29,1
4,60,165,180,96,32,1
5,30,120,95,72,21,0
6,40,135,115,80,26,0
7,55,155,160,92,31,1
8,65,170,200,100,34,1
9,28,115,88,68,22,0


In [15]:
X = df[
    [
        "Age",
        "BP",
        "Sugar_Level",
        "Heart_Rate",
        "BMI"
    ]
]

y = df["Disease"]

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

In [17]:
model = GaussianNB()

model.fit(X_train, y_train)

GaussianNB()

In [18]:
y_pred = model.predict(X_test)

print(y_pred)

[1 0 1 1 1]


In [19]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.8


In [20]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       0.75      1.00      0.86         3

    accuracy                           0.80         5
   macro avg       0.88      0.75      0.76         5
weighted avg       0.85      0.80      0.78         5



In [21]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[1 1]
 [0 3]]


In [22]:
new_patient = [[55, 150, 170, 92, 31]]

prediction = model.predict(new_patient)

if prediction[0] == 1:
    print("Disease Predicted")
else:
    print("No Disease Predicted")

Disease Predicted


c:\Users\thema\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
