In [1]:
name = ["jaggu", "guru", "Mannu", "appu"]

print(name)

['jaggu', 'guru', 'Mannu', 'appu']


In [5]:
name.append("deepu")
print(name)

['jaggu', 'guru', 'Mannu', 'appu', 'deepu']


In [6]:
name.remove("deepu")
print(name)

['jaggu', 'guru', 'Mannu', 'appu']


In [7]:
name.insert(2,"nani")
print(name)

['jaggu', 'guru', 'nani', 'Mannu', 'appu']


In [8]:
student = {
    "name": "Jagannath",
    "age": 23,
    "course": "CSAI"
}
print(student)

{'name': 'Jagannath', 'age': 23, 'course': 'CSAI'}


In [10]:
print(student["name"])

Jagannath


In [11]:
student["college"]="kle"
print(student)

{'name': 'Jagannath', 'age': 23, 'course': 'CSAI', 'college': 'kle'}


In [12]:
student["age"]=24
print(student)

{'name': 'Jagannath', 'age': 24, 'course': 'CSAI', 'college': 'kle'}


In [14]:
print(student.keys())

dict_keys(['name', 'age', 'course', 'college'])


In [15]:
print(student.values())

dict_values(['Jagannath', 24, 'CSAI', 'kle'])


In [16]:
print(student.items())

dict_items([('name', 'Jagannath'), ('age', 24), ('course', 'CSAI'), ('college', 'kle')])


In [17]:
for key, value in student.items():
    print(key, ":", value)

name : Jagannath
age : 24
course : CSAI
college : kle


In [18]:
try:
    a=10
    b=0
    print(a/b)

except ZeroDivisionError:
    print("cannot divide by zero")    

cannot divide by zero


In [20]:
try:
    a=10
    b=2
    r=a/b

except ValueError:
    print("invalid number")

except ZeroDivisionError:
    print("zero cant be dividor")
else:
    print(r)
finally:
    print("this will run")                

5.0
this will run


In [22]:
file=open("data.csv","r")
content=file.read()
print(content)
file.close()

hello Dlithe



In [28]:
file=open("data.csv","w")
file.write("Jagannath")
file.close()

In [29]:
file=open("data.csv","r")
content=file.read()
print(content)
file.close()

Jagannath


In [30]:
file=open("data.csv","a")
file.write("\nhello all")
file.close()

In [31]:
file=open("data.csv","r")
content=file.read()
print(content)
file.close()

Jagannath
hello all


In [32]:
with open("data.csv","r") as file:
    content=file.read()
    print(content)

Jagannath
hello all


In [33]:
with open("data.csv", "r+") as file:
    content = file.read()
    print("Existing Content:")
    print(content)
    file.write("This line is added using r+\n")

Existing Content:
Jagannath
hello all


In [34]:
with open("data.csv","r") as file:
    content=file.read()
    print(content)

Jagannath
hello allThis line is added using r+



In [35]:
with open("data.csv", "w") as file:
    file.write("This is OLD DATA\n")
    file.write("This will be deleted!\n")
print("Old file created!")

Old file created!


In [36]:
with open("data.csv","r") as file:
    content=file.read()
    print(content)

This is OLD DATA
This will be deleted!



In [1]:
import numpy as np

In [ ]:
marks = np.array([
    [85, 78, 92],[67, 74, 80],[90, 88, 95],[56, 65, 70],[76, 82, 79]])
print(marks)

[[85 78 92]
 [67 74 80]
 [90 88 95]
 [56 65 70]
 [76 82 79]]


In [3]:
new_marks=marks+5

In [4]:
print(new_marks)

[[ 90  83  97]
 [ 72  79  85]
 [ 95  93 100]
 [ 61  70  75]
 [ 81  87  84]]


In [5]:
result=marks*2
print(result)

[[170 156 184]
 [134 148 160]
 [180 176 190]
 [112 130 140]
 [152 164 158]]


In [6]:
result=marks/2
print(result)

[[42.5 39.  46. ]
 [33.5 37.  40. ]
 [45.  44.  47.5]
 [28.  32.5 35. ]
 [38.  41.  39.5]]


In [7]:
internal = np.array([[10, 8, 9],[8, 7, 8],[9, 10, 9],[6, 7, 6],[8, 9, 8]])

In [8]:
print(internal)

[[10  8  9]
 [ 8  7  8]
 [ 9 10  9]
 [ 6  7  6]
 [ 8  9  8]]


In [9]:
total=marks+internal

In [10]:
print(total)

[[ 95  86 101]
 [ 75  81  88]
 [ 99  98 104]
 [ 62  72  76]
 [ 84  91  87]]


In [11]:
diff=total-internal
print(diff)

[[85 78 92]
 [67 74 80]
 [90 88 95]
 [56 65 70]
 [76 82 79]]


In [12]:
student_total=np.sum(marks,axis=1)
print(student_total)

[255 221 273 191 237]


In [13]:
student_avg=np.mean(marks,axis=1)
print(student_avg)

[85.         73.66666667 91.         63.66666667 79.        ]


In [15]:
highestmark=np.max(marks)
print(highestmark)

95


In [16]:
minmarks=np.min(marks)
print(minmarks)

56


In [17]:
subject_highest =np.max(marks,axis=0)
print(subject_highest)

[90 88 95]


In [18]:
std=np.std(marks)
print(std)

10.49994708981378


In [19]:
print(marks)

[[85 78 92]
 [67 74 80]
 [90 88 95]
 [56 65 70]
 [76 82 79]]


In [20]:
tsp=marks.T 
print(tsp)

[[85 67 90 56 76]
 [78 74 88 65 82]
 [92 80 95 70 79]]


In [21]:
marks2 = np.array([
    [85, 78, 92],[67, 74, 80],[90, 88, 95],[56, 65, 70],[76, 82, 79]])
print(marks2)

[[85 78 92]
 [67 74 80]
 [90 88 95]
 [56 65 70]
 [76 82 79]]


In [22]:
combined = np.concatenate((marks, marks2), axis=0)
print(combined)

[[85 78 92]
 [67 74 80]
 [90 88 95]
 [56 65 70]
 [76 82 79]
 [85 78 92]
 [67 74 80]
 [90 88 95]
 [56 65 70]
 [76 82 79]]


In [23]:
combined = np.concatenate((marks, marks2), axis=1)
print(combined)

[[85 78 92 85 78 92]
 [67 74 80 67 74 80]
 [90 88 95 90 88 95]
 [56 65 70 56 65 70]
 [76 82 79 76 82 79]]


In [25]:
total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)
print("Student Total:", total)
print("Student Average:", average)
print("Class Highest:", np.max(marks))
print("Class Lowest:", np.min(marks))
print("Subject Average:", np.mean(marks, axis=0))

Student Total: [255 221 273 191 237]
Student Average: [85.         73.66666667 91.         63.66666667 79.        ]
Class Highest: 95
Class Lowest: 56
Subject Average: [74.8 77.4 83.2]


In [26]:
import numpy as np

In [27]:
salaries = np.array([35000, 48000, 52000, 67000, 45000, 75000, 58000, 42000, 90000, 51000])
print(salaries)

[35000 48000 52000 67000 45000 75000 58000 42000 90000 51000]


In [28]:
total = np.sum(salaries)
print("Total Salary:", total)

Total Salary: 563000


In [29]:
average = np.mean(salaries)
print("Average Salary:", average)

Average Salary: 56300.0


In [30]:
maximum = np.max(salaries)
print("Maximum Salary:", maximum)

Maximum Salary: 90000


In [31]:
minimum = np.min(salaries)
print("Minimum Salary:", minimum)

Minimum Salary: 35000


In [32]:
above_50000 = salaries[salaries > 50000]
print("Salaries above 50000:", above_50000)

Salaries above 50000: [52000 67000 75000 58000 90000 51000]


In [33]:
count = np.sum(salaries > 50000)
print("Number of employees:", count)

Number of employees: 6


In [34]:
quantity = np.array([2, 3, 1, 5, 4])
price = np.array([100, 250, 500, 80, 150])
print("Quantity:", quantity)
print("Price:", price)

Quantity: [2 3 1 5 4]
Price: [100 250 500  80 150]


In [35]:
total_price = quantity * price
print("Total price:", total_price)

Total price: [200 750 500 400 600]


In [36]:
final_bill = np.sum(total_price)
print("Final Bill:", final_bill)

Final Bill: 2450


In [39]:
numbers = np.random.randint(1, 101, 20)
print(numbers)

[82 48 45  8 53 40  9 64 86  4 68 69 41 99 64 68 48 44 69 21]


In [40]:
sorted_numbers = np.sort(numbers)
print("Sorted Numbers:", sorted_numbers)

Sorted Numbers: [ 4  8  9 21 40 41 44 45 48 48 53 64 64 68 68 69 69 82 86 99]


In [41]:
unique_numbers = np.unique(numbers)
print("Unique Numbers:", unique_numbers)

Unique Numbers: [ 4  8  9 21 40 41 44 45 48 53 64 68 69 82 86 99]


In [43]:
standard_deviation = np.std(numbers)
print("Standard Deviation:", standard_deviation)

Standard Deviation: 25.59199093466548


In [44]:
numbers = np.arange(1, 101)
print(numbers)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [45]:
even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers:", even_numbers)

Even Numbers: [  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [46]:
odd_numbers = numbers[numbers % 2 != 0]
print("Odd Numbers:", odd_numbers)

Odd Numbers: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [47]:
divisible_by_5 = numbers[numbers % 5 == 0]
print("Numbers divisible by 5:", divisible_by_5)

Numbers divisible by 5: [  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [48]:
between_30_60 = numbers[(numbers >= 30) & (numbers <= 60)]
print("Numbers between 30 and 60:", between_30_60)

Numbers between 30 and 60: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60]
